main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('pencet/', views.submit, name='submit'),
    path('delete/', views.delete, name='delete'),
    path('matkul/<int:value>', views.show_matkul, name='show')
]

story_5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    SEMESTER = [
        ('Gasal', 'Gasal'),
        ('Gasal', 'Genap')
    ]

    nama = models.CharField(max_length = 99)
    dosen = models.CharField(max_length = 99)
    sks = models.IntegerField()
    deskripsi = models.CharField(max_length = 250)
    ruang = models.CharField(max_length = 25)
    semester = models.CharField(
        max_length=5,
        choices=SEMESTER,
    )
    tahun1 = models.IntegerField()
    tahun2 = models.IntegerField()

main/forms.py
from django import forms
from .models import MataKuliah

class InputForm(forms.ModelForm):
    class Meta:
        model = MataKuliah
        fields = ['nama', 'dosen', 'sks', 'deskripsi', 'ruang', 'semester', 'tahun1', 'tahun2']
    
    my_widget = forms.TextInput(attrs={'class':'form-control', 'spellcheck':'false'})
    
    
    nama = forms.CharField(widget=my_widget, max_length=99)
    dosen = forms.CharField(widget=my_widget, max_length=99)
    sks = forms.IntegerField(max_value=24, widget=forms.NumberInput(attrs={'class':'form-control'}))
    deskripsi = forms.CharField(widget=my_widget, max_length= 250)
    ruang = forms.CharField(widget=my_widget, max_length=25)
    semester = forms.TypedChoiceField(
        coerce=str,
        choices=[('Gasal', 'Gasal'), ('Genap', 'Genap')],
        initial='Gasal',
        widget=forms.Select(attrs={'class':'custom-select mr-sm-2'})
    )
    tahun_choices = [
        (2016,2016),
        (2017,2017),
        (2018,2018),
        (2019,2019),
        (2020,2020),
        (2021,2021)
    ]
    tahun1 = forms.TypedChoiceField(coerce=int, choices=tahun_choices, initial=2020, widget=forms.Select(attrs={'class':'custom-select mr-sm-2'}))
    tahun2 = forms.TypedChoiceField(coerce=int, choices=tahun_choices, initial=2021, widget=forms.Select(attrs={'class':'custom-select mr-sm-2'}))

main/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponseRedirect
from .forms import InputForm
from .models import MataKuliah

def home(request):
    # reset penomoran id dari 1
    count = 1
    id_baru = [i.pk for i in MataKuliah.objects.all()]
    for i in id_baru:
        MataKuliah.objects.filter(id=i).update(id=count)
        count+=1
    response = {
        'input_form' : InputForm,
        'matkul_obj' : MataKuliah.objects.all(),
        'condition' : False
    }
    return render(request, 'main/home.html', response)


def submit(request):
    form = InputForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')

def delete(request):
    id = request.POST['dropdown']
    if request.method == 'POST':
        try:
            MataKuliah.objects.all().get(pk=id).delete()
        except MataKuliah.DoesNotExist:
            return HttpResponseRedirect('/')
        response = {
        'input_form' : InputForm,
        'matkul_obj' : MataKuliah.objects.all(),
        'condition' : True
        }
        return render(request, 'main/home.html', response)

def show_matkul(request, value):
    response = {
        'input_form' : InputForm,
        'matkul' : MataKuliah.objects.get(pk=value)
    }
    return render(request, 'main/matkul.html', response)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">
<title>Story 5</title>
{% endblock meta %}

{% block content %}
<div class="card my-cont">
  <ul class="card-header nav nav-tabs" role="tablist">
    <li class="nav-item">
      {% if condition %}
      <a class="nav-link" id="add-matkul" data-toggle="tab" href="#add-menu" role="tab" aria-controls="add-matkul" aria-selected="true">Tambah Matkul</a></li>
      {% else %}
      <a class="nav-link active" id="add-matkul" data-toggle="tab" href="#add-menu" role="tab" aria-controls="add-matkul" aria-selected="true">Tambah Matkul</a></li>
      {% endif %}
    <li class="nav-item">
      {% if condition %}
      <a class="nav-link active" id="delete-matkul" data-toggle="tab" href="#delete-menu" role="tab" aria-controls="delete-matkul" aria-selected="false">Delete Matkul</a></li>
      {% else %}
      <a class="nav-link" id="delete-matkul" data-toggle="tab" href="#delete-menu" role="tab" aria-controls="delete-matkul" aria-selected="false">Delete Matkul</a></li>
      {% endif %}
    <li class="nav-item">
      <a class="nav-link" id="show-matkul" data-toggle="tab" href="#show-menu" role="tab" aria-controls="show-matkul" aria-selected="false">Show Matkul</a></li>
  </ul>
  
  <div class="card-body tab-content">
    <div id="add-menu" class="tab-pane fade show active" role="tabpanel" aria-labelledby="add-matkul">
      <form action="{% url 'main:submit' %}" method="post" class="my-form">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_nama">Mata Kuliah</label>
          {{ input_form.nama }}
        </div>
        <div class="form-group">
          <label for="id_dosen">Pengajar</label>
          {{ input_form.dosen }}
        </div>
        <div class="form-group">
          <label for="id_sks">SKS</label>
          {{ input_form.sks }}
        </div>
        <div class="form-group">
          <label for="id_deskripsi">Deskripsi</label>
          {{ input_form.deskripsi }}
        </div>
        <div class="form-group">
          <label for="id_ruang">Ruang</label>
          {{ input_form.ruang }}
        </div>
        <div class="d-flex flex-row form-group">
          {{ input_form.semester }}
          {{ input_form.tahun1 }}
          {{ input_form.tahun2 }}
        </div>
        <input type="submit" value="Submit">
      </form>
    </div>
    <div id="delete-menu" class="tab-pane fade in" role="tabpanel" aria-labelledby="delete-matkul">
      <h3>Delete Mata Kuliah</h3>
      <form action="{% url 'main:delete' %}" method="POST">
        {% csrf_token %}
        <select name="dropdown" class="form-control">
          {% for i in matkul_obj  %}
            <option value="{{ i.id }}">{{ i.nama }}</option>
          {% endfor %}
        </select>
        <input type="submit" value="Delete" id="del">
      </form>
      {% if condition %}
        <h5>Berhasil menghapus.</h5>
      {% endif %}
    </div>
    <div id="show-menu" class="tab-pane fade" role="tabpanel" aria-labelledby="show-matkul">
      {% for matkul in matkul_obj.all %}
        <a href="{% url 'main:show' matkul.id %}" class="card bg-light mb-3 matkul-cont">
          <div class="card-body">
            <h4 class="card-title matkul-nama">{{ matkul.nama }}</h4>
            <span class="badge badge-secondary cust-badge">{{ matkul.semester }} {{ matkul.tahun1 }}/{{ matkul.tahun2 }}</span>
          </div>
        </a>
      {% endfor %}
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
{% if condition %}
  <script src="{% static 'js/form.js' %}"></script>
{% endif %}
{% endblock content %}

main/templates/main/matkul.html
{% extends "base.html" %}
{% load static %}
{% block meta %}
  <link rel="stylesheet" href="{% static 'css/matkul.css' %}">
  <title>Story 5</title>
{% endblock meta %}

{% block content %}

<div class="card border-dark mb-3 matkul">
    <div class="card-header">
        <div class="head">{{ matkul.nama }}</div>
        <span class="badge badge-secondary cust-badge">{{ matkul.semester }} {{ matkul.tahun1 }}/{{ matkul.tahun2 }}</span>
    </div>
    <div class="card-body text-dark">
        <h5 class="card-title">{{ matkul.sks }} SKS</h4>
        <h6 class="card-title">Pengajar: {{ matkul.dosen }}</h5>
        <p class="card-text text">{{ matkul.deskripsi }}</p>
    </div>
</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>